### PR TITLE
enable -preview=in, fix #2617

### LINKED ISSUE #2617: Get rid of deprecate warnings
Deprecate warnings should fixed before they become errors:

```
source\dub\dependency.d(917,18): Deprecation: scope variable `this` assigned to non-scope parameter `oth` calling `opEquals`
source\dub\dependency.d(920,30): Deprecation: scope variable `this` assigned to non-scope parameter `a` calling `doCmp`
source\dub\dependency.d(921,27): Deprecation: scope variable `this` assigned to non-scope parameter `b` calling `doCmp`
source\dub\dependency.d(939,26): Deprecation: scope variable `this` assigned to non-scope parameter `oth` calling `opEquals`
source\dub\internal\configy\Exceptions.d(130,34): Deprecation: reference to local variable `buffer` assigned to non-scope anonymous parameter
source\dub\internal\configy\Exceptions.d(134,34): Deprecation: reference to local variable `buffer` assigned to non-scope anonymous parameter
source\dub\internal\configy\Exceptions.d(248,27): Deprecation: `@safe` function `formatMessage` calling `formattedWrite`
C:\D\dmd2\windows\bin\..\..\src\phobos\std\format\write.d(537,34):        which calls `std.format.spec.FormatSpec!char.FormatSpec.writeUpToNextSpec!(void delegate(in char[]) @safe).writeUpToNextSpec`
C:\D\dmd2\windows\bin\..\..\src\phobos\std\format\spec.d(258,33):        which would be `@system` because of:
C:\D\dmd2\windows\bin\..\..\src\phobos\std\format\spec.d(258,33):        scope variable `this` assigned to non-scope parameter `e` calling `put`
source\dub\internal\configy\Exceptions.d(250,27): Deprecation: `@safe` function `formatMessage` calling `formattedWrite`
C:\D\dmd2\windows\bin\..\..\src\phobos\std\format\write.d(537,34):        which calls `std.format.spec.FormatSpec!char.FormatSpec.writeUpToNextSpec!(void delegate(in char[]) @safe).writeUpToNextSpec`
C:\D\dmd2\windows\bin\..\..\src\phobos\std\format\spec.d(258,33):        which would be `@system` because of:
C:\D\dmd2\windows\bin\..\..\src\phobos\std\format\spec.d(258,33):        scope variable `this` assigned to non-scope parameter `e` calling `put`
source\dub\internal\configy\Exceptions.d(283,27): Deprecation: `@safe` function `formatMessage` calling `formattedWrite`
C:\D\dmd2\windows\bin\..\..\src\phobos\std\format\write.d(537,34):        which calls `std.format.spec.FormatSpec!char.FormatSpec.writeUpToNextSpec!(void delegate(in char[]) @safe).writeUpToNextSpec`
C:\D\dmd2\windows\bin\..\..\src\phobos\std\format\spec.d(258,33):        which would be `@system` because of:
C:\D\dmd2\windows\bin\..\..\src\phobos\std\format\spec.d(258,33):        scope variable `this` assigned to non-scope parameter `e` calling `put`
source\dub\internal\configy\Exceptions.d(286,27): Deprecation: `@safe` function `formatMessage` calling `formattedWrite`
C:\D\dmd2\windows\bin\..\..\src\phobos\std\format\write.d(537,34):        which calls `std.format.spec.FormatSpec!char.FormatSpec.writeUpToNextSpec!(void delegate(in char[]) @safe).writeUpToNextSpec`
C:\D\dmd2\windows\bin\..\..\src\phobos\std\format\spec.d(258,33):        which would be `@system` because of:
C:\D\dmd2\windows\bin\..\..\src\phobos\std\format\spec.d(258,33):        scope variable `this` assigned to non-scope parameter `e` calling `put`
source\dub\internal\configy\Exceptions.d(323,31): Deprecation: `@safe` function `formatMessage` calling `formattedWrite`
C:\D\dmd2\windows\bin\..\..\src\phobos\std\format\write.d(537,34):        which calls `std.format.spec.FormatSpec!char.FormatSpec.writeUpToNextSpec!(void delegate(in char[]) @safe).writeUpToNextSpec`
C:\D\dmd2\windows\bin\..\..\src\phobos\std\format\spec.d(258,33):        which would be `@system` because of:
C:\D\dmd2\windows\bin\..\..\src\phobos\std\format\spec.d(258,33):        scope variable `this` assigned to non-scope parameter `e` calling `put`
source\dub\internal\configy\Exceptions.d(325,31): Deprecation: `@safe` function `formatMessage` calling `formattedWrite`
C:\D\dmd2\windows\bin\..\..\src\phobos\std\format\write.d(537,34):        which calls `std.format.spec.FormatSpec!char.FormatSpec.writeUpToNextSpec!(void delegate(in char[]) @safe).writeUpToNextSpec`
C:\D\dmd2\windows\bin\..\..\src\phobos\std\format\spec.d(258,33):        which would be `@system` because of:
C:\D\dmd2\windows\bin\..\..\src\phobos\std\format\spec.d(258,33):        scope variable `this` assigned to non-scope parameter `e` calling `put`
source\dub\internal\configy\Exceptions.d(332,31): Deprecation: `@safe` function `formatMessage` calling `formattedWrite`
C:\D\dmd2\windows\bin\..\..\src\phobos\std\format\write.d(537,34):        which calls `std.format.spec.FormatSpec!char.FormatSpec.writeUpToNextSpec!(void delegate(in char[]) @safe).writeUpToNextSpec`
C:\D\dmd2\windows\bin\..\..\src\phobos\std\format\spec.d(258,33):        which would be `@system` because of:
C:\D\dmd2\windows\bin\..\..\src\phobos\std\format\spec.d(258,33):        scope variable `this` assigned to non-scope parameter `e` calling `put`
source\dub\internal\configy\Exceptions.d(335,31): Deprecation: `@safe` function `formatMessage` calling `formattedWrite`
C:\D\dmd2\windows\bin\..\..\src\phobos\std\format\write.d(537,34):        which calls `std.format.spec.FormatSpec!char.FormatSpec.writeUpToNextSpec!(void delegate(in char[]) @safe).writeUpToNextSpec`
C:\D\dmd2\windows\bin\..\..\src\phobos\std\format\spec.d(258,33):        which would be `@system` because of:
C:\D\dmd2\windows\bin\..\..\src\phobos\std\format\spec.d(258,33):        scope variable `this` assigned to non-scope parameter `e` calling `put`
```

### PR DESCRIPTION
**Pull request by WebFreak001**
reopening #2620

sorry for the bunch of force pushes, I just wanted to get the PR Info action to work for this, as it should summarize changing deprecations like this and should show fixed things. (building on linux)

### CODE REVIEW

**Comment by WebFreak001** [comment]
from #2620:

```
source\dub\internal\vibecompat\core\file.d(104,39): Error: cannot use `in` parameters with `extern(Windows)` functions
source\dub\internal\vibecompat\core\file.d(104,39):        parameter `to` declared as `in` here
source\dub\internal\vibecompat\core\file.d(104,39): Error: cannot use `in` parameters with `extern(Windows)` functions
source\dub\internal\vibecompat\core\file.d(104,39):        parameter `from` declared as `in` here
```

**Comment by Geod24** [comment]
```
/home/runner/work/dub/dub/source/dub/recipe/sdl.d:349: error: undefined reference to '_D3std6format__TQkTaTAyaZQtFNaNfMxAaQpZQs'
/home/runner/work/dub/dub/source/dub/recipe/sdl.d:350: error: undefined reference to '_D3std6format__TQkTaTAyaZQtFNaNfMxAaQpZQs'
/home/runner/work/dub/dub/source/dub/recipe/sdl.d:351: error: undefined reference to '_D3std6format__TQkTaTAyaZQtFNaNfMxAaQpZQs'
/home/runner/work/dub/dub/source/dub/recipe/sdl.d:380: error: undefined reference to '_D3std6format__TQkTaTAyaZQtFNaNfMxAaQpZQs'
/home/runner/work/dub/dub/source/dub/internal/utils.d:1086: error: undefined reference to '_D3std3net4curl4HTTP15onReceiveHeaderMFNdDFMxAaMxQeZvZv'
```

What ? :|

**Comment by WebFreak001** [comment]
looks like that only happens on LDC, probably because phobos is compiled differently, causing different mangling

**Comment by Geod24** [comment]
#2783

**Pull request closed without merging**
