### PR TITLE
Add version spec ability for commands

### LINKED ISSUE #1979: `dub describe` can't describe specific package version
I think it must be like `dub describe mypackage@1.2.3`
related to https://github.com/mesonbuild/meson/issues/7496

### PR DESCRIPTION
**Pull request by deviator**
fix #1979
No breaking changes, add ability for specify package version in `describe`, `test`, `lint`, `generate`, `build -n`, `run -n` commands. I think it need in this [meson issue](https://github.com/mesonbuild/meson/issues/7496).

### CODE REVIEW

**Comment by deviator** [comment]
ping @s-ludwig 
I think those errors doesn't depend on code, otherwise can you explain problem, please?
https://github.com/dlang/dub/pull/1980/checks?check_run_id=908636201#step:6:485
https://github.com/dlang/dub/pull/1980/checks?check_run_id=908636201#step:6:1370

**Comment by andre2007** [comment]
You could try to restart the pipeline tests by closing and reopening the pull request.

**Comment by deviator** [comment]
Thanks, @andre2007!

**Comment by deviator** [comment]
@andre2007, need I do something else for this PR for make it able to merge into master?

**Comment by wilzbach** [comment]
> @andre2007, need I do something else for this PR for make it able to merge into master?

Yes, you'll need to add at least one test, s.t. this feature can be tested and doesn't regress.
It can either be a `unittest` test or a full integration test. The earlier one is easier.

**Comment by deviator** [comment]
@wilzbach can you please explain what I do wrong?
https://github.com/dlang/dub/pull/1980/checks?check_run_id=910150242#step:6:1370

**Comment by wilzbach** [comment]
Just copy/pasting the error log from CI for you:

```
No package manifest (dub.json or dub.sdl) was found in
/home/travis/build/dlang/dub/test/version-spec
Please run DUB from the root directory of an existing package, or run
"dub init --help" to get information on creating a new package.
No valid root package found - aborting.
[ERROR] Build failure.
```

Test suite runner tries to build your package. You're missing a `.no_build` file.

**Comment by deviator** [comment]
> Test suite runner tries to build your package. You're missing a `.no_build` file.

Thank you) I was think `.no_run` and `.no_test` files are enough... My mistake

**Comment by deviator** [comment]
@wilzbach @andre2007 need review, right?

**Comment by andre2007** [comment]
The implementation looks good so far except 2 nitpicks:
- why do you prefix format function with a dot?
- tilde should be surrounded by a space character

The test actually does not test whether the new functionality is working.
It just calls it but does not test anything?

At the end please combine all changes into 1 commit.

**Comment by deviator** [comment]
> * why do you prefix format function with a dot?
for prevent call class method instead of `std.format.format`
I done this like at [here](https://github.com/dlang/dub/blob/master/source/dub/commandline.d#L901)
but now I see `Command` class or `PackageBuildCommand` class have no method `format`, may be it was before.

**Pull request closed without merging**
