### PR TITLE
Allow adding dflags on dependencies when using SDL format

### LINKED ISSUE #2079: Cannot add dflags on dependencies when using SDL format
Dub v1.24.0 introduced [dflags on dependencies](https://dlang.org/changelog/2.095.0.html#dependency-build-settings), but this is only supported for the JSON format, not the SDL format.

CC @omerfirmak @mdparker

### PR DESCRIPTION
**Pull request by omerfirmak**
Fixes #2079

### CODE REVIEW

**Comment by Geod24** [comment]
Can you rebase to target stable ? `git rebase --onto upstream/stable upstream/master`.
Also can you add a test that only `dflags` is accepted ?

**Comment by omerfirmak** [comment]
Rebased.

>  Also can you add a test that only dflags is accepted ?

What do you mean exactly? Currently, other build settings are accepted but will have no affect.

**Comment by Geod24** [comment]
> What do you mean exactly? Currently, other build settings are accepted but will have no affect.

Hum, I thought that they would print an error message. Well, if it's the same for JSON, and there's no easy way to warn about it, let's keep it as is. This is for power users (still) anyways.

**Comment by omerfirmak** [comment]
> > What do you mean exactly? Currently, other build settings are accepted but will have no affect.
> 
> Hum, I thought that they would print an error message. Well, if it's the same for JSON, and there's no easy way to warn about it, let's keep it as is. This is for power users (still) anyways.

Yes, it's the same for JSON as well.

**Review by Geod24 — APPROVED** [review]

**Pull request merged**
