### PR TITLE
Skip explicitly linking with libcurl for LDC on Windows.

### PR DESCRIPTION
**Pull request by s-ludwig**
Attempts to fix the failing AppVeyor build that currently ruins the PR overview page by making it see that all PRs are broken.

### CODE REVIEW

**Comment by s-ludwig** [comment]
@MartinNowak: Can we disable the jenkins/branch test? It fails unconditionally for all PRs and presumably doesn't add much value, considering that Travis already tests branch and merge commits.

**Comment by s-ludwig** [comment]
Was just about to hit "merge" when I noticed that this is accidentally using the JSON platform suffix syntax instead of `platform="..."`. Searching for the origins of `libs "curl"` revealed that it was actually added to make the Windows build work in ancient times, and obviously this is not needed at all anymore. So instead of removing this for just LDC/Windows it looks like this can be removed completely, even for the oldest supported versions.

**Comment by ZombineDev** [comment]
TBH, I was surprised that you had to manually add curl to the link list. AFAIK, phobos links it internally.

**Comment by s-ludwig** [comment]
I don't remember exactly, but there used to be a time when this was not the case. The latest versions link to it at runtime and the versions before that had the import symbols embedded in phobos.lib. But that was not always the case. There were also some changes for LDC in this area a while ago. But as long as our official support list works without it, it fortunately doesn't matter anymore.

**Comment by ZombineDev** [comment]
Martin changed it with this PR: https://github.com/dlang/phobos/pull/3009/files

**Pull request merged**
