### PR TITLE
Commandline: Do not duplicate GeneratorSettings fields

### PR DESCRIPTION
**Pull request by Geod24**
Instead of adding fields individually to the Command, just store a GeneratorSettings,
and getopt it as needed.

### CODE REVIEW

**Comment by Geod24** [comment]
@WebFreak: Those fields are `protected` so *technically* part of the "public" API, but I hope we can agree that `dub.commandline` is not part of the `dub-as-library` API...

**Review by WebFreak001 — APPROVED** [review]

**Comment by WebFreak001** [comment]
yeah I think the API changes are fine here

**Comment by Geod24** [comment]
> Tests currently failing though.

Turns out I forgot to remove one duplicated field :grin:

**Review by PetarKirov — COMMENTED** [review]
Nice!

**Pull request merged**
