### PR TITLE
Update dependencies to the latest release

### PR DESCRIPTION
**Pull request by Geod24**
Needed for https://github.com/dlang/phobos/pull/7545

### CODE REVIEW

**Comment by wilzbach** [comment]
The newest eventcore seems to be incompatible with 2.076 - https://travis-ci.com/github/dlang/dub/jobs/367979885

IIRC we need to maintain building from scratch with 2.076 for GDC, but that's only for dub from source, but not for dub built with dub.

**Comment by Geod24** [comment]
That's odd, because the diff between v0.9.6 and v0.9.7 is [a single commit](https://github.com/vibe-d/eventcore/commit/862b5d470c7b19019811963596f9da624913147d) which cannot possibly be the source of this...

**Comment by wilzbach** [comment]
At the moment eventcore 0.8.48 is used here.

**Comment by Geod24** [comment]
Note to self: Don't comment on Github issues before taking your morning coffee.
Alright, I'll try to look into it a bit later this week.

**Comment by wilzbach** [comment]
As I said, I think it's fine to simply ignore the dub build of dub for older versions. AFAIK GDC only builds dub from source.

**Comment by Geod24** [comment]
Looking at the CI, this is actually currently red on master. But this PR fixes a failure in the Github Actions (because it fails to link without the fix in this PR, so force merging.

**Pull request merged**
