### PR TITLE
Make 'dub remove' remove all packages by default in non-interactive mode 

### PR DESCRIPTION
**Pull request by Geod24**
This is a new feature that simplify writing scripts a tiny bit.
Also included one fix from my Alpine PR since otherwise the lack of `--version` could error out.

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Review by wilzbach — APPROVED** [review]
Makes sense :+1:

**Comment by wilzbach** [comment]
```
[ERROR] /Users/runner/work/dub/dub/test/version-spec.sh:12 command failed
[ERROR] /Users/runner/work/dub/dub/test/version-spec.sh:13 command failed
[ERROR] /Users/runner/work/dub/dub/test/version-spec.sh:14 command failed
```

I added the dub test command as an extra debug commit.

**Comment by Geod24** [comment]
There's also:
```
[ERROR] /Users/runner/work/dub/dub/test/issue1158-stdin-for-single-files.sh:8 Stdin for single files failed.
[ERROR] Script failure.
```

**Comment by Geod24** [comment]
Failures look spurious... Will debug.

**Comment by Geod24** [comment]
Weird, the test pass, despite the error... I really hate `dub`'s test suite. But will merge this, as I don't want to be stuck yak shaving again.

**Pull request merged**
