### PR TITLE
Merge remote-tracking branch 'upstream/stable' into merge_stable

### PR DESCRIPTION
**Pull request by MartinNowak**

### CODE REVIEW

**Comment by ZombineDev** [comment]
Merging myself, after restarting Higgs manually on Buildkite. The Jenkins failure appears on other builds and is not related to this PR.
@wilzbach should Jenkins be retired from Dub's list of CIs as well?

**Comment by wilzbach** [comment]
Yes, it already is since two weeks, but I think the Jenkins instance is still running and doing a cron-job on missed PRs... :/

**Comment by wilzbach** [comment]
The last webhook was sent in July (!):

image

**Comment by wilzbach** [comment]
> Merging myself, after restarting Higgs manually on Buildkite.

https://github.com/dlang/ci/pull/302

**Pull request merged**
