### PR TITLE
Default `dub init` to SDL

### PR DESCRIPTION
**Pull request by WebFreak001**
Átila wants to throw out dub.json, so this is the first step to discouraging dub.json

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by Geod24** [comment]
:/
https://github.com/dlang/dub/issues/724

**Comment by Geod24** [comment]
Also, can we *not* merge such controversial changes without a discussion, pretty please ?

**Comment by WebFreak001** [comment]
I agree this is a pretty controversial change. I had a chat with Átila about the decision to drop dub.json, I'm not fully happy with that decision, but I think it will certainly offer benefits:

- the SDL format is easier to read and write
- it supports comments
- it supports `` `grave accent` `` style strings, which is good for path strings

Átila suggested roughly the following plan:
- deprecate dub.json
- automatically open issues on all dub packages that are using dub.json
- PR with `dub convert` to all packages
  - side-effect: dead repositories will be identified like this
  - repositories that are dead, but actually used, should be moved to the dlang-community organization in that case
- disallow building root packages with `dub.json` (but keep dependencies working)

now there is still time to discuss things and what to do exactly. I think another idea would be simply disallowing packages in dub.json format to be published to the registry anymore, but keep everything as-is otherwise.

There had been the failed attempt #789, but I think with Átila's backing here we can actually make it through.

I think just changing the `dub init` default for now is going to be better for users, we could maybe add a dub.settings.json setting for that for those that _really_ don't want to change. Additionally I'm currently improving the dub docs (e.g. also merge sdl and json into single pages, with tabbing) and would like to have SDL as the default there.

Now I just merged in this PR without discussion as Átila strongly expressed his feelings about this to me and that we definitely want to drop JSON eventually. Having this dub release be a big change in many different aspects (colors, json parsing improvements, possibly `dub explain` in it) I think it's additionally beneficial to make such a change now, when a lot is changing, rather than later.

**Comment by Geod24** [comment]
> but I think it will certainly offer benefits: [...]

I don't find `sdl` easy to write. Each time I need to write it, I have to refer to the documentation.
And `sdl` has one major drawback which IMO is a showstopper: Almost no one else supports it. We want more people, not less.

> Átila suggested roughly the following plan: [...]

What's the timeline here ? Because if we are to deprecate `dub.json`, that should have a looooooong deprecation period.
And we should be consistent and not rely on JSON everywhere in the dub code before we even think about this, otherwise it's just an arbitrary limitation.

> now there is still time to discuss things and what to do exactly.

We can start by reverting this.

> I think another idea would be simply disallowing packages in dub.json format to be published to the registry anymore, but keep everything as-is otherwise.

Don't see it as a good idea. It will just drive people not to use the registry.

>  Having this dub release be a big change in many different aspects (colors, json parsing improvements, possibly dub explain in it) I think it's additionally beneficial to make such a change now, when a lot is changing, rather than later.

First: I don't think those things are related. We might have a lot of improvements coming over the next few months, because that's how long it will take to get dub in a good state. Whether the change comes in v1.30.0 or v1.33.0 matters little.
Second: I have very little interest in contributing to dub if that's the direction we're going. Deprecating JSON means that a large chunk of the contributions I made recently are, in fact, useless. And as you know quite well, it also goes in the opposite direction of my long term goals, so this really just feels like sabotage.

**Comment by WebFreak001** [comment]
ok gonna revert then, we will probably want to raise these points to Átila as well and figure out if it's even really a problem to begin with.

**Comment by Herringway** [comment]
Trying to remember what keys and values dub expects is enough of a cognitive load. don't make me learn yet another configuration language with its own quirks and edge cases without a real good reason for it. comments and backtick strings are not compelling.

**Pull request merged**
