### PR TITLE
Print the platform probe atomically

### PR DESCRIPTION
**Pull request by SSoulaimane**
DMD may print some stuff in between calls of `pragma(msg)` and corrupt the json data.

This is blocking DMD PR https://github.com/dlang/dmd/pull/10539, all buildkite tests which depend on dub are failing.

After debugging, I found out It's printing a probe like this:
```json
__dub_probe_begin__
{
  "compiler": "dmd",
  "frontendVersion": 2088,
  "compilerVendor": "Digital Mars D",
  "platform": [
import    core.internal.array.utils	(/home/ss/Downloads/dmd/generated/linux/debug/64/../../../../../druntime/import/core/internal/array/utils.d)
    "linux", "posix"
  ],
  "architecture": [
    "x86_64"
   ],
}
__dub_probe_end__
```
It fails at parsing the probe as json and aborts everything.

### CODE REVIEW

**Comment by WebFreak001** [comment]
this code was extremely difficult to read before and after. Now with even more differently formatted string literals inside that string literal it's confusing.

Can we maybe change parts of the generated code to ``` `` ``` strings or `q"EOS <multiple lines> EOS"` for this big block where it's not obvious at a first glance which parts are "strings outside the strings", "strings inside the strings", "code inside the strings" or which parts are "code outside the strings"

**Comment by wilzbach** [comment]
> this code was extremely difficult to read before and after. Now with even more differently formatted string literals inside that string literal it's confusing.

The proper solution is to use the new `-Xi=compilerInfo` anyhow, so I don't see any problems with this as the only maintainance step should be to remove this.

**Comment by SSoulaimane** [comment]
@wilzbach dub has to support older compiler versions, so I don't think a this method will be replaced by anything recent.

**Comment by wilzbach** [comment]
> dub has to support older compiler versions, so I don't think a this method will be replaced by anything recent.

Well, the last ten releases have this new interface which is incidentally also what we officially support as the lowest bootstrap compiler, so that's not really a big concern.

Anyhow, my point was that there's no point in investing more time into making this old interface look nicer as it's maintainance only.

**Comment by SSoulaimane** [comment]
@WebFreak001 it looks fine to me, the only confusing bit is the to figure out the `q{ }` where it starts and ends.

**Pull request merged**
