### PR TITLE
Fetch with dependencies

### PR DESCRIPTION
**Pull request by Panke**

### CODE REVIEW

**Comment by Panke** [comment]
I am needing this or something similar for bazel support (#1889)

**Comment by Geod24** [comment]
Needs a rebase. And for the name, `--recursive` is more common (e.g. it's what `git` and many CLI tools use).

**Comment by Panke** [comment]
> Needs a rebase. And for the name, `--recursive` is more common (e.g. it's what `git` and many CLI tools use).

--recursive was my first thought, but we got some use of recursive that is quite dissimilar to this one, like https://github.com/dlang/dub/pull/1873 which means sub packages and not dependencies. 

I couldn't care less for the name though. If no one else chimes in, it will be recursive.

**Comment by Geod24** [comment]
I think for `dub fetch`, `--recursive` is pretty unambiguous. You cannot fetch sub-packages independently.

**Comment by Geod24** [comment]
Also need a release notes entry, this is a change that might be interesting to a few people (e.g. in build scripts).

**Comment by WebFreak001** [comment]
should we make this a switch? imo this should be the default

workflow for someone with data caps:

connect to internet
fetch all required dependencies
disconnect from internet
build stuff locally -- oops, dependencies of fetched dependencies aren't there by default

**Comment by Geod24** [comment]
We can't have self-reference / circular reference, can we ? That would be one argument against it.
Having it the default for `dub fetch` makes sense. IDK about `--cache=local` though.

**Comment by WebFreak001** [comment]
definitely needs a test for recursive dependencies here then

**Comment by Panke** [comment]
> We can't have self-reference / circular reference, can we ? That would be one argument against it.
> Having it the default for `dub fetch` makes sense. IDK about `--cache=local` though.

I don't think --cache=local should be a default.

**Comment by Geod24** [comment]
> I don't think --cache=local should be a default.

Oh I phrased my message very poorly. I meant "IDK if having it the default for cache local makes as much sense". But after reviewing again, I think it does too.

> what do we call the switch?

I'd say, in doubt, do what `git` does. So `--shallow`.

**Comment by Panke** [comment]
What we could do is: download everything that is not in the --cache=<thiscache>

**Comment by Panke** [comment]
This turns out to be more annoying than I thought. This works only for dependencies that are dependencies of the default configuration, but won't fetch anything for e.g. vibe-d.

I could use some pointers on how to get a list of transitive dependencies.

**Comment by WebFreak001** [comment]
try checking the selections and/or generating them for the fetched package, they are recursive

**Comment by andre2007** [comment]
When I execute following commands:
```
dub fetch vibe-d
dub describe vibe-d
```

vibe-d and all dependencies are downloaded. Therefore `dub describe vibe-d` does the fetch with dependencies. Maybe you could check how it works here and reuse the already available functionality?

**Comment by andre2007** [comment]
Related https://github.com/dlang/dub/issues/1930

**Comment by Geod24** [comment]
As far as I can tell this was done by #2786

**Pull request closed without merging**
