### PR TITLE
Remove line 'Exclusing package.d blah...' from default dub build

### PR DESCRIPTION
**Pull request by p0nce**
Now a diagnostic message.
Discussion in #2153

### CODE REVIEW

**Review by PetarKirov — APPROVED** [review]

**Comment by thewilsonator** [comment]
*Exclu_d_ing, also vibe example fails

**Comment by p0nce** [comment]
The vibe.d example that fails says:
```
Compiling Diet HTML template home.dt...
--
  | ../../web/vibe/web/i18n.d(222,4): Error: `"Missing translation key for en_US; home: This is the internationalization example app."`
  | ../../web/vibe/web/i18n.d(175,24):        called from here: `tr(key, null, 0, context)`
  | ../../web/vibe/web/web.d(340,99):        called from here: `tr(key, context)`
  | ../../../.dub/packages/diet-ng-1.8.0/diet-ng/source/diet/traits.d(75,23):        called from here: `translate(text, context)`
  | ../../../.dub/packages/diet-ng-1.8.0/diet-ng/source/diet/parser.d(1239,17):        called from here: `translate(kln, stripExtension(baseName(loc.file)))`
  | ../../../.dub/packages/diet-ng-1.8.0/diet-ng/source/diet/parser.d(1110,20):        called from here: `parseTextLine(remainder, ret, tmploc)`
  | ../../../.dub/packages/diet-ng-1.8.0/diet-ng/source/diet/parser.d(1044,38):        called from here: `parseTagLine(input, loc, has_nested)`
  | ../../../.dub/packages/diet-ng-1.8.0/diet-ng/source/diet/parser.d(77,76):        called from here: `parseDietRaw(f)`
```
so it doesn't seem related to me.

**Comment by thewilsonator** [comment]
(am half asleep atm)

> so it doesn't seem related to me.

maybe but it is consistent. Maybe try using a fix to the typo in the commit message nd see if that fixes it.

**Comment by PetarKirov** [comment]
Hey @s-ludwig, could this PR be there cause for the problem we're seeing on BuildKite: https://github.com/rejectedsoftware/diet-ng/pull/92 ?

**Comment by p0nce** [comment]
Trying without the typo

**Pull request merged**
