### PR TITLE
Minor updates to Travis-CI config

### PR DESCRIPTION
**Pull request by Geod24**
Let's see how this pans out...

### CODE REVIEW

**Comment by Geod24** [comment]
Can someone retrigger the CI ? There definitely is a lot of SEGV recently...

**Comment by wilzbach** [comment]
> Can someone retrigger the CI ? There definitely is a lot of SEGV recently...

Done, btw if you can reach this page you might trigger a "request to join" to Andrei/Vladimir/Walter:

https://github.com/orgs/dlang/teams/team-dub/members

**Comment by Geod24** [comment]
Done, thanks

**Comment by andre2007** [comment]
@Geod24 side information,  you can trigger the ci builds again by closing and opening the pr again.
Maybe in future we can enhance the dlang bot to simple retrigger the ci builds by writing a github comment with e.g. text `retry`.

**Comment by andre2007** [comment]
@Geod24 and of course, thank you so much for working on this topic

**Pull request merged**
