### PR TITLE
update version to v1.31.0-beta.1

### PR DESCRIPTION
**Pull request by ibuclaw**

### CODE REVIEW

**Review by PetarKirov — APPROVED** [review]

**Comment by PetarKirov** [comment]
It looks like the CI is failing on Windows because Dub creates a path that's very long.

@Geod24 do you recall if you encountered such problems when working on the separate build cache feature?

**Comment by ibuclaw** [comment]
> It looks like the CI is failing on Windows because Dub creates a path that's very long.
> 
> @Geod24 do you recall if you encountered such problems when working on the separate build cache feature?

First failure that I see was on: https://github.com/dlang/dub/commit/8ad1d431f1da6a73d43e13424be253e25cb08586
This change was untested by the CI: https://github.com/dlang/dub/commit/98a355e722458410477e62ea8a7346ffdceca46d

It could be there has been a regression in dmd-master, someone with a windows machines can bisect.

**Comment by Geod24** [comment]
The issue would come from https://github.com/dlang/dub/pull/2542 but the CI was green when I tested.

**Comment by ibuclaw** [comment]
> The issue would come from #2542 but the CI was green when I tested.

I've also seen what looks like the same error in dlang/installer too.

https://github.com/dlang/installer/actions/runs/3825037333/jobs/6507952110

**Comment by Geod24** [comment]
> I've also seen what looks like the same error in dlang/installer too.

That's different. We're doing `rm -r` of a directly that does not exists (because it is now created elsewhere).
I don't know if the lack of `-f` is accidental or on purpose (to ensure something was build).

**Comment by Geod24** [comment]
That job just passed on master, so re-triggering...

**Pull request merged**
