### PR TITLE
Replace deprecated keyword `body` with `do`

### PR DESCRIPTION
**Pull request by nordlow**

### CODE REVIEW

**Comment by nordlow** [comment]
Getting scope errors in CI jobs. What to do?

**Review by thewilsonator — APPROVED** [review]

**Comment by thewilsonator** [comment]
https://github.com/dlang/undeaD/pull/47

**Comment by Geod24** [comment]
> source/dub/internal/undead/xml.d

The problematic code is in dub, so you need to apply the diff here as well.

**Review by RazvanN7 — APPROVED** [review]

**Comment by RazvanN7** [comment]
> The problematic code is in dub, so you need to apply the diff here as well.

@nordlow This.

**Comment by nordlow** [comment]
I don't follow. I can't find any more references to the body keyword on this branch.

**Comment by RazvanN7** [comment]
The patch that @thewilsonator applied to undead needs to be applied to the local copy of undead in dub. See `source/dub/internal/undead/xml.d` : it's the same code as in dlang/undeaD#47

**Comment by nordlow** [comment]
> The patch that @thewilsonator applied to undead needs to be applied to the local copy of undead in dub. See `source/dub/internal/undead/xml.d` : it's the same code as in [dlang/undeaD#47](https://github.com/dlang/undeaD/pull/47)

Ahh, sorry. I was searching for the body keyword. I'll fix.

**Comment by nordlow** [comment]
Changes applied.

**Comment by WebFreak001** [comment]
it says the toType function in xml.d is missing `scope` on its argument, not sure how it works upstream? (should probably even be `scope return`)

**Comment by nordlow** [comment]
> it says the toType function in xml.d is missing `scope` on its argument, not sure how it works upstream? (should probably even be `scope return`)

Done.

**Review by thewilsonator — APPROVED** [review]

**Review by WebFreak001 — APPROVED** [review]

**Comment by nordlow** [comment]
Read now.

**Review by RazvanN7 — APPROVED** [review]

**Pull request merged**
