### PR TITLE
VisualD project generation now account for the debugVersions key (deb…

### PR DESCRIPTION
**Pull request by p0nce**
…ug identifiers)

### CODE REVIEW

**Comment by Geod24** [comment]
Is there any way to test this ?  And I assume you are using it ?

**Comment by p0nce** [comment]
Hello, yes I've tested it locally before submitting :

image

**Comment by p0nce** [comment]
Seems the cmake generator emit those, it's just the VisualD generator that doesn't.

**Comment by Geod24** [comment]
> yes I've tested it locally before submitting

I mean is there a way to have integration tests ?

**Comment by Geod24** [comment]
@p0nce : If the answer is no, I'm still happy to go ahead with this change :)
Just wanted to avoid any future regression.

**Pull request closed without merging**
