### PR TITLE
Merge pull request #1600 from RazvanN7/fix_cast

### PR DESCRIPTION
**Pull request by wilzbach**
Fix wrong cast

Cherry-pick of https://github.com/dlang/dub/pull/1600 to `stable` (using the merge commit)

### CODE REVIEW

**Comment by ZombineDev** [comment]
@wilzbach while you're at it, can you also include https://github.com/dlang/dub/pull/1579?

**Comment by ZombineDev** [comment]
And also either https://github.com/dlang/dub/pull/1575, or we fix the AppVeyor nightlies URL ;)

**Comment by wilzbach** [comment]
> @wilzbach while you're at it, can you also include #1579?

Sure. Done.

**Comment by wilzbach** [comment]
Buildkite dlang/dub fails because it checks out `stable` and not the merged PR head, but this will be fixed by https://github.com/dlang/ci/pull/344, so I'm manually merging this. All other tests on Buildkite pass.

**Comment by wilzbach** [comment]
Tagged as v1.12.0-1, s.t. projects depending on dub will automatically use the latest version and we don't mess with @MartinNowak's release scripts for patch versions.

See: https://github.com/dlang/dub/releases/tag/v1.12.0-1

**Comment by LaurentTreguier** [comment]
👍 I'll update as soon as code.dlang.org picks it up then

**Comment by ZombineDev** [comment]
@wilzbach  Uhm, https://github.com/dlang/dub/releases/tag/v1.12.0-1 gives 404.

**Comment by wilzbach** [comment]
Sorry for forgetting to mention this here. In accordance to better SemVer (i.e. not tagging a prerelease of the currently released version), I renamed the tag while it was still hot to [`v1.12.1-alpha.1`](https://github.com/dlang/dub/releases/tag/v1.12.1-alpha.1).

Full discussion: https://github.com/d-language-server/dls/pull/17#issuecomment-442515282

**Pull request merged**
