### PR TITLE
Improve travis-ci.sh

### PR DESCRIPTION
**Pull request by Geod24**
This will probably break horribly, but there's only one way to find out...

### CODE REVIEW

**Comment by Geod24** [comment]
Ugh this stage setup is also terrible. If something fails in the first stage and is retriggered (and pass), the second stage never starts so the whole build is marked as 'cancelled' and one has to restart *everything*.

Also the reason why #1795 happens is pretty clear, looking at `.travis-ci.yaml`...
@wilzbach : Since you are our resident Azure pipeline expert, do you think you'll have some time to do your magic before the end of the month ? Otherwise I might take a look at it.

**Comment by wilzbach** [comment]
> @wilzbach : Since you are our resident Azure pipeline expert, do you think you'll have some time to do your magic before the end of the month ? Otherwise I might take a look at it.

Yeah it was on my list already. I will be travelling a lot for the next few days, but I think I can get this before New Year's Eve.

**Comment by wilzbach** [comment]
> Ugh this stage setup is also terrible. If something fails in the first stage and is retriggered (and pass), the second stage never starts so the whole build is marked as 'cancelled' and one has to restart everything

BTW the reason for running the second stage for every PR was that once we enabled the Travis builds which upload to GitHub we weren't sure how reliable they are and it was also the only way to test the PRs. However, a solution would be to enable them only for a PR which is from the dub repository and not with branches from forks.

**Comment by Geod24** [comment]
> Travis builds which upload to GitHub

I don't quite get why we do that ?
Those 6 builds are pretty much useless  right now. The OSX one is useful, but it should be part of test. They also use a different set of flags (release flags) but that could be just 1 entry in the test matrix.

IIUC, the original intent was for this stage to trigger only on tags: https://github.com/dlang/dub/blob/2e9a26acf388dcd54cdc3f4332ee4cfd9b28047a/.travis.yml#L105-L107

Which makes much more sense to me. I couldn't find much in the [original PR](https://github.com/dlang/dub/pull/1433#discussion_r181036384). I guess whatever bug you were working around at the time might have been worked out, since LTO has seen a lot of love over the last 2 years ?

**Comment by wilzbach** [comment]
> I don't quite get why we do that ?

So that the people can download dub binaries (from GitHub releases). This is interesting for example if you want to have a newer version of dub with an older compiler.

> IIUC, the original intent was for this stage to trigger only on tags:

Yes, though as I mentioned this wasn't done as otherwise the scripts couldn't be tested. I fully agree that there should be no need to run them for a normal PR build. I was just explaining the historical reason ... or at least trying to.


> I guess whatever bug you were working around at the time might have been worked out, since LTO has seen a lot of love over the last 2 years ?

Yes.

**Comment by Geod24** [comment]
Okay, I think revisiting the travis config can be done later though. This is good to go as is and already gave me useful insight.

**Pull request merged**
