### PR TITLE
Handle gzip compression from code.dlang.org

### PR DESCRIPTION
**Pull request by dazoe**
fix for #1210

### CODE REVIEW

**Comment by s-ludwig** [comment]
Interesting, code.dlang.org doesn't do any gzip encoding, except for a single URL, do you possibly have a proxy in-between?

If I understand it correctly, the `set` call will cause cURL to send an empty "Accepts-Encoding" header, thus disabling any gzip encoding, right? IMO that would be a little too much, as we might have to re-enable gzip encoding in general at some point to save some bandwidth.

**Comment by MartinNowak** [comment]
No, this enables encoding handling by curl, see https://curl.haxx.se/libcurl/c/CURLOPT_ACCEPT_ENCODING.html. Setting it to `null` would disable any encoding.

**Comment by dazoe** [comment]
Ah, I didn't think about the whole proxy thing. I use a mobile connection and apparently they MTIM my http traffic and force gzip compression. I confirmed this by running some curl fetches from a remote server.

Calling set with an empty string causes libcurl to send an Accept-Encoding header containing libcurl's built-in supported encodings which libcurl handles transparently. Reference: https://curl.haxx.se/libcurl/c/CURLOPT_ACCEPT_ENCODING.html

**Comment by MartinNowak** [comment]
Most MNOs do such things, better we'd move to HTTPS at some point, and maybe also add gzip encoding to dub-registry or it's reverse proxy (taking care of [BREACH](https://en.wikipedia.org/wiki/BREACH)).

**Comment by s-ludwig** [comment]
Okay, I didn't find the official documentation page and just guessed based on other sources, sounds fine then.

We could switch to HTTPS at any time, at least for code.dlang.org. There would just have to be a configuration option to force plain HTTP to avoid breakage on more niche systems. Taking care of BREACH attacks is of course important, but since we are coming from a completely unencrypted connection and there is no confidential information in the requests that DUB itself performs, this fortunately isn't very critical in the beginning.

**Comment by MartinNowak** [comment]
Was thinking more of a http->https redirect on code.dlang.org. But even for that, there shouldn't be any secrets in the payloads (only uncompressed session cookies in HTTP headers).

**Pull request merged**
