### PR TITLE
extraDependencyFiles attribute added

### PR DESCRIPTION
**Pull request by andre2007**
Using attribute `dependencyFiles` a list of files can be specified
causing rebuild on change.

Fixes https://github.com/dlang/dub/issues/1117

### CODE REVIEW

**Comment by andre2007** [comment]
Issue #1117 was created by @s-ludwig  and also this week he agains wrote that this change is needed.
https://forum.dlang.org/post/puqkvg$ild$1@digitalmars.com
>>Most notably, there is a directive missing to specify arbitrary files as build dependencies.<<

I am almost sure he agrees to this pr :)

**Comment by ZombineDev** [comment]
I know, I read his posts, so I'm 90% sure as well, but I haven't  seen him specify his desired syntax.

**Comment by andre2007** [comment]
Yes, if there is a better name I change the pull request. Should I change it to "extraDependencyFiles"?

**Comment by ZombineDev** [comment]
> Should I change it to "extraDependencyFiles"?

IMO it would be more clear for first-time users.

**Comment by andre2007** [comment]
Issue https://github.com/dlang/dub/issues/1623 created as proposed by @s-ludwig

**Comment by andre2007** [comment]
Field renamed to ```extraDependencyFiles```.

**Comment by thewilsonator** [comment]
@andre2007 this good to go?

**Comment by andre2007** [comment]
yes :)

**Pull request merged**
