### PR TITLE
Fix #813 proper

### LINKED ISSUE #813: dub add-local not compatible with auto local discovery
on Windows with cygwin:

I have 2 local directories:
git/vibe.d  // clone of https://github.com/rejectedsoftware/vibe.d.git
project/test // my test project

I want to compile test project with locally modified vibe.d from git/vibe.d directory.
For that I use
$ dub add-local "C:\Users\vadim\git\vibe.d"
then
project/test $ dub build ----> OK

But when I am trying to build vibe.d itself:
git/vibe.d $ dub build ----------> ERROR
Unknown dependency: vibe-d:core

It seems like dub add-local prevents dub from using the current directory.
To make vibe.d building again I have to "dub remove-local" first.

$ dub add-local "C:\Users\vadim\git\vibe.d"
$ dub list
Packages present in the system and known to dub:
  vibe-d 0.7.29-alpha.3: C:\Users\vadim\git\vibe.d\
  vibe-d:core 0.7.29-alpha.3: C:\Users\vadim\git\vibe.d\
  vibe-d:utils 0.7.29-alpha.3: C:\Users\vadim\git\vibe.d\
  vibe-d:data 0.7.29-alpha.3: C:\Users\vadim\git\vibe.d\
...
$ dub remove-local "C:\Users\vadim\git\vibe.d"
$ dub list
Packages present in the system and known to dub:
  vibe-d 0.7.29-alpha.3+commit.11.g30dd461: C:\Users\vadim\git\vibe.d\
  vibe-d:core 0.7.29-alpha.3+commit.11.g30dd461: C:\Users\vadim\git\vibe.d\
  vibe-d:utils 0.7.29-alpha.3+commit.11.g30dd461: C:\Users\vadim\git\vibe.d\
  vibe-d:data 0.7.29-alpha.3+commit.11.g30dd461: C:\Users\vadim\git\vibe.d\
  vibe-d:http 0.7.29-alpha.3+commit.11.g30dd461: C:\Users\vadim\git\vibe.d\
  vibe-d:mail 0.7.29-alpha.3+commit.11.g30dd461: C:\Users\vadim\git\vibe.d\

vibe.d/dub.json:
"dependencies": {
                ":utils": "_",
                ":data": "_",
                ":core": "_",
                ":http": "_",
                ":mail": "_",
                ":diet": "_",
                ":mongodb": "_",
                ":redis": "_",
                ":web": "*"
        },

### PR DESCRIPTION
**Pull request by rikkimax**
WIP

### CODE REVIEW

**Comment by rikkimax** [comment]
Oh no...

```
[INFO] Running /home/runner/work/dub/dub/test/[issue813-fixed-dependency.sh](http://issue813-fixed-dependency.sh/)...
verify that we can build sub without add-local
    Starting Performing "debug" build using dmd for x86_64.
    Building sub ~master: building configuration [library]
verify that we can build sub with add-local
             Registered package: sub (version: ~master)
    Starting Performing "debug" build using dmd for x86_64.
    Building sub ~master: building configuration [library]
             Deregistered package: sub (version: ~master)
verify that we can build main application
    Starting Performing "debug" build using dmd for x86_64.
    Building sub:sub ~master: building configuration [library]
    Building sub ~master: building configuration [library]
    Building main ~master: building configuration [application]
     Linking main
```

That is not what I want to see, since that is certainly reproducing the problem on Windows... wait, is this a Windows specific bug?

**Comment by rikkimax** [comment]
```
verify that we can build sub without add-local
Performing "debug" build using dmd for x86_64.
sub ~master: building configuration "library"...
verify that we can build sub with add-local
Registered package: sub (version: ~master)
Non-optional dependency 'sub:sub' of 'sub' not found in dependency tree!?.
Deregistered package: sub (version: ~master)
verify that we can build main application
Performing "debug" build using dmd for x86_64.
sub:sub ~master: building configuration "library"...
sub ~master: building configuration "library"...
main ~master: building configuration "application"...
Linking...
```

Ooooo yes, something is up here @s-ludwig!

**Comment by rikkimax** [comment]
Okay, this is fixed in ~master, just gotta figure out what fixed it.

**Comment by WebFreak001** [comment]
shouldn't we merge the test case for this then?

**Comment by rikkimax** [comment]
(Ignoring that I already deleted the branch)

My test cases were just slight changes to the ones Sonke added back in 2016 for this issue and I am worried that this could be Windows specific (as I was explaining on Discord).

**Comment by Geod24** [comment]
Yeah we need to get the test-suite running on Windows...

**Comment by rikkimax** [comment]
Perhaps we should consider putting together a cross platform shell and
distribute it with the compiler.

Good example project and would allow us easier transitioning test suites.

**Pull request closed without merging**
