### PR TITLE
Add experimental feature to improve build cache efficiency

### PR DESCRIPTION
**Pull request by MartinNowak**
Using version identifiers to configure certain features can often lead to
unnecessary rebuilds of dependencies that don't use those version
identifiers. In order to improve the build cache efficiency, dub gained a new
experimental `--filter-versions` switch.

When `--filter-versions` is passed to any build, test, or generate command, dub
will grep for all the version identifiers packages actually use and only apply
those during building. This allows for example to reuse a cached build for a
library between two applications using different version identifiers when the
library isn't using any of those itself.

Reduces time for vibe-d's examples test suite by about 50% for me.

### CODE REVIEW

**Comment by jacob-carlborg** [comment]
Grepping feels like a hack. I guess you don't want to use DMD as a library?

**Comment by MartinNowak** [comment]
Not in it's current state. Yes grepping substitutes a parser (which couldn't find all version identifiers either), but version declarations are also very simple constructs (see https://dlang.org/spec/grammar.html#VersionSpecification) so grep is a suitable tool.

**Comment by jacob-carlborg** [comment]
> which couldn't find all version identifiers either

The Dub package provides semantic analyze, but that might take longer than just using grep.

**Comment by thewilsonator** [comment]
> Yes grepping substitutes a parser

That won't handle `version` or `debug` as part of a comment, but I don't think that it will be a particularly common occurrence. This is experimental anyway, LGTM.

**Comment by andre2007** [comment]
Can this be merged?

**Comment by thewilsonator** [comment]
Whoops, thanks!

**Pull request merged**
