### PR TITLE
On Windows support disabling of forcing of all object files in a static library to be in a DLL

### PR DESCRIPTION
**Pull request by rikkimax**
Augments https://github.com/dlang/dub/pull/2614

I'll do dub-docs once given all clear.

@kinke is there anything else you want me to do?

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by Geod24** [comment]
I have a few issues with this:
- Having separate things for project and package has historically worked very poorly;
- There are no tests;
- It's blankly stating that the previous PR introduced a regression;
- I'm not quite sure what even te problem is here, and why this is a good solution;

**Review by WebFreak001 — CHANGES_REQUESTED** [review]
needs a test to at least demonstrate what this is even doing

**Comment by kinke** [comment]
I think what almost all users would want is something like https://github.com/symmetryinvestments/dub/commit/f841c6dfe4bfdfe700b86db42277ab337dcc5034 - being able to override default `-fvisibility=public -dllimport=all` (designed for a scenario where every dub dependency is a DLL) with e.g. `-fvisibility=hidden -dllimport=defaultLibsOnly` for an isolated DLL (potentially containing static lib deps, and only exporting explicitly exported symbols).

**Comment by Geod24** [comment]
@kinke : We need to get the flag propagation fixed. I had the same problem with `-preview=in` and that's why we have the ugly dependency `dflags` hack.

**Comment by kinke** [comment]
Yeah - including all those duplicates when a flag is passed down to all deps and then passed upwards again. I've seen *pages* (on a FullHD monitor) of identical flags in ugly-ass cmdlines.

**Comment by rikkimax** [comment]
What I'm thinking is we need to have a directive to set the visibility. So that dub can actually understand it and add behavior like dllimport (which is kinda a hack we, unfortunately, need currently) and ``/WHOLEARCHIVE:``.

If we combine that directive with my work and add a way to disallow it, not just allow eliding, that should cover our basis here.

I think I'll leave it to you @kinke to get this to completion.

**Comment by rikkimax** [comment]
Problem is, once it is needed you have people who don't know what a linker is asking why it doesn't work. When you give them an explanation they complain very loudly and are more likely to leave D even if it isn't our fault.

Ignoring it isn't a good solution.

**Comment by kinke** [comment]
I probably shouldn't have changed the default compile-DLL flags with LDC on Windows with dub v1.30 yet, as it introduced such problems for existing DLL projects. It newly enables working with shared-lib dependencies, but broke at least some existing isolated DLLs.

But what's IMO important is taking the time to come up with a good, generic-as-possible solution. E.g., this specific problem could also be handled by making dub default to building all dependencies of a shared library project as shared libs themselves (recursively).

https://github.com/symmetryinvestments/dub/commit/f841c6dfe4bfdfe700b86db42277ab337dcc5034 then allows to customize exports and imports for a DLL or executable. I haven't tested that in production yet but will do, hopefully pretty soon. It would cover 2 problems we currently have at Symmetry:
* The main executable is linked against shared druntime/Phobos via `-link-defaultlib-shared`, so that we can load D plugins (shared libs) which also use that shared druntime/Phobos (incl. shared GC, shared thread lists etc. etc.). All static lib dependencies of the executable need to be compiled with `-dllimport=defaultLibsOnly` (or `-link-defaultlib-shared`, which defaults to that), and dub currently doesn't handle that.
* We have about 25 plugins - pretty isolated shared libs compiled with `-fvisibility=hidden -dllimport=defaultLibsOnly`, so that they only export a few select symbols and only share druntime/Phobos. All static lib deps of these plugins need to be compiled with the same flags. They all depend on one base project, so by adding `-fvisibility=hidden -dllimport=defaultLibsOnly` for that single project and making sure these propagate up and down the dub dependencies graph, that is handled in a single central place.

**Comment by rikkimax** [comment]
Okay so we've got something else in the works, which we need to evaluate
which is much broader in scope.

Makes sense to wait.

**Pull request closed without merging**
