### PR TITLE
add osx testing

### PR DESCRIPTION
**Pull request by John-Colvin**

### CODE REVIEW

**Comment by John-Colvin** [comment]
Can someone please cancel the old travis builds that are hanging on this PR?

**Comment by s-ludwig** [comment]
Looks like the tests are executed in an endless loop (maybe recursively?).

**Comment by wilzbach** [comment]
ping @John-Colvin - interesting in reviving this from the dead?

**Comment by Geod24** [comment]
Closing as stale. I raised https://github.com/dlang/dub/pull/1946 which makes it pass on my machine, and I started working on a Github workflow to run the test suite on all three platforms.

**Pull request closed without merging**
