### PR TITLE
Merge remote-tracking branch 'upstream/stable' into merge_stable

### PR DESCRIPTION
**Pull request by MartinNowak**

### CODE REVIEW

**Comment by Geod24** [comment]
Can someone re-run the CI ? Looks spurious

**Comment by Geod24** [comment]
I think @MartinNowak or @wilzbach need to disable Jenkins?

**Comment by ZombineDev** [comment]
It was already disabled, IIRC...

**Comment by ZombineDev** [comment]
https://github.com/dlang/dub/pull/1539#issuecomment-415813832

**Pull request merged**
