### PR TITLE
[Perf] Use a custom parser to get module name from content

### PR DESCRIPTION
**Pull request by wilzbach**
Coming from #1078, here's a simple, custom parser to get the module name. It's about 10x faster than using the RegExp.

Another big gain would be to use a file stream instead of parsing the entire file, but that's an opportunity for another PR.

### CODE REVIEW

**Comment by s-ludwig** [comment]
Do you have objections to merge #1078? Then, if this passes the additional tests, I think we can just merge it as well.

**Comment by wilzbach** [comment]
> Do you have objections to merge #1078?

Not at all ;-)
As said I just made the PR, s.t. this doesn't get forgotten.

> Then, if this passes the additional tests, I think we can just merge it as well.

Let's hope for the best.

**Comment by s-ludwig** [comment]
Still errors out with
> core.exception.AssertError@source/dub/internal/utils.d(479): unittest failure

**Comment by BBasile** [comment]
You should add tests for laughable (but valid) cases like
```d
module /**/hu./**/he/**/./**/ho;
```

**Comment by Geod24** [comment]
Done in https://github.com/dlang/dub/pull/2897

**Pull request closed without merging**
