### PR TITLE
Remove use of the deprecated -gc DMD flag for debugInfoC

### PR DESCRIPTION
**Pull request by wilzbach**
See also: https://github.com/dlang/dmd/pull/7815

### CODE REVIEW

**Comment by jacob-carlborg** [comment]
Perhaps `debugInfoC` should be deprecated? This change is a bit misleading.

**Comment by wilzbach** [comment]
> Perhaps debugInfoC should be deprecated? 

Not sure as it still has an effect for other compilers, see e.g.
https://github.com/dlang/dub/blob/master/source/dub/compilers/gdc.d#L31

**Comment by jacob-carlborg** [comment]
> Not sure as it still has an effect for other compiler

Aha, ok.

**Comment by MartinNowak** [comment]
We should ask @ibuclaw on the future of this, as he has worked a lot to improve D support in gdb, and it has long landed in recent distributions.

**Comment by ibuclaw** [comment]
The original problem with dmd was that they invented their own dwarf debug tags for dynamic and associative arrays and delegates.

https://dlang.org/spec/abi.html#symbolic_debugging

The only debugger that understood these tags was the now dead zerobugs (originally proprietary, now open source abandonware).

Common sense has long since prevailed and dmd hasn't emitted this for years.

The outdated documentation I just linked should be deleted.

**Pull request merged**
