### PR TITLE
Merge remote-tracking branch 'upstream/stable' into merge_stable

### PR DESCRIPTION
**Pull request by MartinNowak**

### CODE REVIEW

**Comment by s-ludwig** [comment]
@MartinNowak: Not sure about the deployment process there. This PR missed the final version bump to 1.7.0 - does the stable->merge_stable->master chain have to be repeated, or is merging stable directly into master okay?

**Comment by wilzbach** [comment]
I think merging stable is fine.
I always run this little script for DMD and Phobos:

https://github.com/wilzbach/git-tools/blob/master/merge_stable

(Currently just on the road)

**Comment by wilzbach** [comment]
FYI: the PR was just hanging in limbo - https://github.com/dlang/dub/pull/1323 (it's merged now)

**Comment by s-ludwig** [comment]
Ah, didn't catch that, thanks!

**Pull request merged**
