### PR TITLE
GH CI: Update runner OS and actions/checkout version

### PR DESCRIPTION
**Pull request by Geod24**

### CODE REVIEW

**Comment by Geod24** [comment]
Okay I really need to release a new Vibe.d :)

**Review by thewilsonator — APPROVED** [review]
ubuntu-22.04 doesn't seem to pass though

**Comment by Geod24** [comment]
Needs https://github.com/rejectedsoftware/ddox/pull/233

**Comment by WebFreak001** [comment]
@Geod24 is this still blocked? Needing a new tag? (https://github.com/rejectedsoftware/ddox/issues/234)

what would we need to update in dub or is dub fetching ddox online?

**Comment by Geod24** [comment]
Need a new tag, but I think I know a workaround...

**Comment by Geod24** [comment]
The workaround (which I was about to remove...) works.

**Review by WebFreak001 — APPROVED** [review]

**Comment by WebFreak001** [comment]
but wait should we actually upgrade the ubuntu version? I think it's best to keep it on the oldest version, so that built executables work on older linux distros as well.

**Comment by Geod24** [comment]
Well 18.04 is deprecated. So we need to upgrade at least to 20.04.

**Comment by Geod24** [comment]
Okay, let's move ahead with this when the CI (except for master) is green.

**Pull request merged**
