### PR TITLE
Return null instead of empty array

### PR DESCRIPTION
**Pull request by skoppe**
Silly change to get my account verified

### CODE REVIEW

**Comment by Geod24** [comment]
Damn it I broke the nightlies again...

**Review by WebFreak001 — APPROVED** [review]
code change looks reasonable, but how does this help you verify your account?

**Comment by WebFreak001** [comment]
that doesn't answer my question though :p

**Comment by Geod24** [comment]
Because I approved it.

**Comment by Geod24** [comment]
> that doesn't answer my question though

@skoppe has another PR which is substantial. Everytime he does a change and push, CI doesn't run, because he doesn't have a commit in master yet. Now he has a commit in master, so CI will run.

**Comment by WebFreak001** [comment]
oh right that makes sense then, I thought this had something to do with meson package search somewhere explicitly requiring null, which would have been weird.

**Pull request merged**
