### PR TITLE
Update stable

### PR DESCRIPTION
**Pull request by schveiguy**
This should have gone into stable.

### CODE REVIEW

**Comment by Geod24** [comment]
Can you just cherry-pick the commit ? Even if the hash differs, `git` is clever enough to merge it correctly.

**Comment by schveiguy** [comment]
OK, I will try. Never done cherry pick before.

**Comment by Geod24** [comment]
Didn't have to close. You can:

- Reopen (because force pushing to a closed PR lock the PR in a closed state)
- `git fetch upstream && git checkout upstream/stable`
- `git cherry-pick 22c3e6bb`
- `git push -f origin HEAD:updateStable`

And voila

**Comment by schveiguy** [comment]
FYI when doing the cherry pick I got this message:

```
On branch updateStable
You are currently cherry-picking commit 22c3e6b.

Untracked files:
	test/issue1372-ignore-files-in-hidden-dirs/issue1372-test-normal
	test/issue672-upgrade-optional/test.log

nothing added to commit but untracked files present
The previous cherry-pick is now empty, possibly due to conflict resolution.
If you wish to commit it anyway, use:

    git commit --allow-empty

```

So I just did what it said. Sorry.

**Pull request closed without merging**
