### PR TITLE
Dependency: Isolate SemVer version logic in its own struct

### PR DESCRIPTION
**Pull request by Geod24**
```
Currently, Dependency is a mesh of logic, having evolved from a SemVer + branch only
version specification to semver, branch, path, repository.
In order to bring it under control, and attempt to have a smarter dependency matching,
we must first isolate the different ways we specify dependencies.
```

Code has been mostly moved. I assume the CI will yell at me, so I'll likely break this down.

### CODE REVIEW

**Comment by s-ludwig** [comment]
Same idea, but it got lost on the sideway: https://github.com/dlang/dub/pull/1284

**Comment by Geod24** [comment]
@s-ludwig : Ideally I'd like to move this logic to a single module, namely https://github.com/dcarp/semver/ . I'll vendor it in DUB for the time being, but ideally I'd like to move it to dlang-community as many people would probably have similar needs.

Then the idea would be to make `Dependency` use `SumType` so that there is only one "provider" active at a time (path, repository, or version range).

**Comment by s-ludwig** [comment]
> @s-ludwig : Ideally I'd like to move this logic to a single module, namely https://github.com/dcarp/semver/ . I'll vendor it in DUB for the time being, but ideally I'd like to move it to dlang-community as many people would probably have similar needs.

It would be really nice to switch to a self-hosted workflow where we can just use dub packages. There can still be a bootstrap script, and we could even include copies of external dependencies, instead of downloading them on demand, if someone deems that necessary. Although there should really be no need for that, considering that there is a binary included in every compiler distribution.

> Then the idea would be to make `Dependency` use `SumType` so that there is only one "provider" active at a time (path, repository, or version range).

Sounds good.

**Review by s-ludwig — APPROVED** [review]

**Comment by PetarKirov** [comment]
@Geod24 I suggest splitting dub into subpackages, similar to vibe-d, all hosted in this repo. A good example of other package managers whose repo is split like I envision is Yarn: https://github.com/yarnpkg/berry/tree/master/packages

**Comment by rikkimax** [comment]
Doing sub packagers would be a good idea indeed.

Semver, git and repository management could all be candidates for this
treatment.

**Comment by Geod24** [comment]
> It would be really nice to switch to a self-hosted workflow where we can just use dub packages.

I agree. I should restart work on https://github.com/dlang/dub/pull/1972 (Two years, wow!).

> There can still be a bootstrap script, and we could even include copies of external dependencies, instead of downloading them on demand, if someone deems that necessary. Although there should really be no need for that, considering that there is a binary included in every compiler distribution.

The only negative feedback to the above PR was asking for a bootstrap, so I think I'll pick the latest version and add a CI check to make sure we don't break it.

> @Geod24 I suggest splitting dub into subpackages, similar to vibe-d, all hosted in this repo. A good example of other package managers whose repo is split like I envision is Yarn: https://github.com/yarnpkg/berry/tree/master/packages

I'm really not found of subpackages at the moment. They have quite a few quirks, and overlap with configurations. But I'll take a look.

**Pull request merged**
