### PR TITLE
Fix issue #533: Support .hgignore file in dub init.

### PR DESCRIPTION
**Pull request by rjframe**
Note that this also includes my PR #1050 (add globs to the ignorefiles).

Git remains the default. I'm going to create a separate issue concerning #533's comments about running `{git|hg} init` to another ticket, since it is a separate issue.

### CODE REVIEW

**Comment by rjframe** [comment]
This is also affected by and expands the scope of issue #830.

**Comment by rjframe** [comment]
The check failure is "Permission denied" in the "test/0-init-ignorefiles.sh" script; I cannot reproduce it on my machine and the script does nothing that isn't also done by the other init tests - how can I debug this?

**Comment by rjframe** [comment]
I'm not sure what other package managers do (I'm only familiar with pip, and compose as a consumer). I agree it would be better not to list it during init (I think a few of the items asked for should be moved to the global configuration file, this among them); I added it since it was part of the relevant issue, but would be glad to remove it.

**Comment by rjframe** [comment]
The `dub init` process no longer asks for the repository type, defaulting to git.

**Comment by Geod24** [comment]
There doesn't seem to be a high demand for it, and in fact the trend is very clearly down, as can be seen from e.g. Bitbucket removing support. [This article](https://www.theregister.co.uk/2019/08/21/bitbucket_mercurial_repositories/) claims 4% of users.
It also doesn't make sense for `dub` to have a half-baked support, with "just" `.hgignore`, so I think we should close this.

**Pull request closed without merging**
