### PR TITLE
update version to v1.31.0-rc.1

### PR DESCRIPTION
**Pull request by ibuclaw**

### CODE REVIEW

**Comment by WebFreak001** [comment]
can we get #2562 into the next release before we have a full release? I would really like to have it in to be able to fix DUB API usage in serve-d. (it'll make code errors in the editor work properly for all users)

**Comment by ibuclaw** [comment]
@WebFreak001 commit it to the stable branch and it'll be picked up.

**Comment by WebFreak001** [comment]
stable and master are protected, I can't commit to them.

**Comment by ibuclaw** [comment]
You can change base of your PR to target stable.

**Comment by Geod24** [comment]
I'll review today.

**Comment by WebFreak001** [comment]
I think it won't go into master if I target stable though? So I would target master first and then make the same PR onto stable again I guess?

**Comment by Geod24** [comment]
Target stable and we'll merge stable into master

**Pull request merged**
