### PR TITLE
Correct issue #1673 (with dupe #1797 and #2019)

### PR DESCRIPTION
**Pull request by p0nce**

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]
Test case?

**Review by PetarKirov — COMMENTED** [review]
LGTM as well, but as @thewilsonator please add a test for this.

**Comment by p0nce** [comment]
Well I tested it locally.

**Comment by Geod24** [comment]
We really need to overhaul this test-suite. Let's not block improvements in the meantime.

**Comment by p0nce** [comment]
Thanks.

**Pull request merged**
