### PR TITLE
Upgrade sdlang-d.

### PR DESCRIPTION
**Pull request by s-ludwig**
This supersedes #945.

### CODE REVIEW

**Comment by s-ludwig** [comment]
Looks like this isn't easily portable to anything below DMD 2.067.0. Since this would currently rule out GDC (The available releases still appear to be 2.066 front end based), I guess this should be put on hold for a while.

**Comment by wilzbach** [comment]
> Looks like this isn't easily portable to anything below DMD 2.067.0. Since this would currently rule out GDC (The available releases still appear to be 2.066 front end based), I guess this should be put on hold for a while.

That sucks :/
May I stupidly ask whether maintaining compatibility with GDC is really worth the pain? 
LDC has done a great job at catching up lately and they now also support building completely statically linked binaries (one of the few reasons for GDC AFAIK).

**Comment by s-ludwig** [comment]
Well, at least I think we don't lose anything right now by not upgrading. All bug fixes or improvements that I noticed are not relevant for DUB.

It's sad that GDC's development cannot really keep up since a while, but after all, GDC is still in the Debian repositories, so may not be the worst idea to at least enable building DUB, even if most packages will probably fail.

**Comment by wilzbach** [comment]
> Looks like this isn't easily portable to anything below DMD 2.067.0. 

FYI 2.068.0 is now the oldest supported platform, so it might be possible to revive this?

**Comment by Geod24** [comment]
I think we have drifted far enough that, should you want to revive this, it could use a new PR.

**Pull request closed without merging**
