### PR TITLE
Bump vibe.d version used for 'dub init'

### PR DESCRIPTION
**Pull request by wilzbach**
From: https://github.com/vibe-d/vibe.d/issues/2024

### CODE REVIEW

**Comment by wilzbach** [comment]
@s-ludwig any chance you can look into enabling an [AppVeyor team](https://ci.appveyor.com/team). It would allow folks like myself to restart failing builds ;-)
For DMD: I did the following:
- added a role "DLang Team" 
- added all teams from GitHub to this role

I used these permissions for the DLang Team role, though just "run project builds" would be enough:

image

**Comment by mathias-lang-sociomantic** [comment]
IMO versions shouldn't be hardcoded. Don't we have a mean to get the latest version ?

**Comment by s-ludwig** [comment]
@wilzbach I've added a bunch of teams with project settings and build execution access now. I left out administrative rights, if you need them, let me know and I'll add you as a single user instead.

**Comment by wilzbach** [comment]
> I've added a bunch of teams with project settings and build execution access now.

Thanks a lot. Works! Could you do the same for the `vibe-d` organisation?

> IMO versions shouldn't be hardcoded. Don't we have a mean to get the latest version ?

In theory there could be a version 1.0 release of vibe.d which breaks the example template provided.

**Comment by s-ludwig** [comment]
@mathias-lang-sociomantic That could be implemented, but the whole `dub init -t` feature is planned to be replaced by a more general approach, so it would be rather wasteful to invest more time than necessary in this. The new approach basically would simply look for a ":example" (or similar) sub package for the first dependency specified to `dub init`, uses that as the base for the newly created package, and would then just adjust the recipe according to the remaining init parameters.

**Comment by s-ludwig** [comment]
Shouldn't the team change apply to vibe-d organization projects as well? I've also invited you to the "VibeD-Devs" team now (you were just member of the vibe-core repository specifically).

**Pull request merged**
