### PR TITLE
Remove leading hyphen in platform specs

### PR DESCRIPTION
**Pull request by Geod24**
It doesn't serve any purpose. I was tripped by it when iterating over the AA.

### CODE REVIEW

**Review by WebFreak001 — CHANGES_REQUESTED** [review]
this is a public method that's assumed to be simple enough that it might be used elsewhere in other projects, please move the `-` stripping into the matchesSpecification method.

**Comment by WebFreak001** [comment]
no I meant make it so the leading hyphen is optional (stripped if present, otherwise left as is)

e.g. do
```d
specification = specification.chompPrefix("-");
```

as input sanitizing

**Comment by Geod24** [comment]
Right. I'll keep it as is until I flush out all uses, then I'll make the change you suggested.

**Comment by Geod24** [comment]
Okay, we're rid of them, I added the `chompPrefix`

**Review by kinke — APPROVED** [review]

**Pull request merged**
