### PR TITLE
Hotfix for #2051

### LINKED ISSUE #2051: Running unit tests from DUB single file packages fails
### System information

- **dub version**: dub 1.17.0
- **OS Platform and distribution**: Debian 9
- **compiler version** dmd-2.088.1

### Bug Description

Running unit tests from DUB single file packages fails.
See [forum post](https://forum.dlang.org/post/rq5a3n$gcs$1@digitalmars.com) for additional information

### How to reproduce?
Running this:
```D
#!/usr/bin/env dub
/+ dub.sdl:
    name: "main"
+/

version(unittest) {}
else void main()
{
}

unittest
{
	auto input = [1721];
	assert(input[0] == 1721);
}
```
gives:
```
user@user:~/dub$ dub test --single ./test.d
Package main (configuration "application") defines no import paths, use {"importPaths": [...]} or the default package directory structure to fix this.
Generating test runner configuration 'test-test-application' for 'application' (executable).
Source file '/home/user/dub/test/test.d' not found in any import path.
```

### Expected Behavior
the result should be:
```
user@user:~/dub$dub test --single ./test.d
Package main (configuration "application") defines no import paths, use {"importPaths": [...]} or the default package directory structure to fix this.
Generating test runner configuration 'test-test-application' for 'application' (executable).
Performing "unittest" build using dmd for x86_64.
main ~master: building configuration "main-test-application" (default build policy: time)...
Linking...
Running ../../../../tmp/.dub/build/test-~master/test-test-application-unittest-linux.posix-x86_64-dmd_2088-9FDC9F7EC06E24A4F67D7D1E5B88EBD1/test-test-application 
All unit tests have been run successfully.
```

The reason of the bug is that in single mode dub, running test command, try to import the main source file as module and failed because can not find it in any import paths. The main source file should be excluded from this importing but current check for this fails because it can't compare absolute and relative paths correctly (it compares them by char).

### PR DESCRIPTION
**Pull request by drug007**
Hot fix #2051

### CODE REVIEW

**Comment by drug007** [comment]
The PR makes dub running unit tests in the main source file in case of single file package (by default dub excludes them). The second test added to make sure that unit tests run really.

**Comment by thewilsonator** [comment]
It seems you removed an `_` from the test file, creating a large diff. Please put it back to make reviewing easier.

**Comment by drug007** [comment]
Ok, I'll do renaming in another PR then (to conform to other file names).

**Review by thewilsonator — APPROVED** [review]

**Comment by drug007** [comment]
Rebased the branch

**Comment by drug007** [comment]
@thewilsonator between what is preferable - many small specific commits like I did or one large commit like it was told in other PRs I saw?

**Comment by thewilsonator** [comment]
Specifically in this case, file renames in separate PRs is preferable.

**Comment by drug007** [comment]
I've realized that GitHub is not able to handle renaming gracefully and shows both files separately that makes review very difficult. My question is more about is splitting a PR to many small commits better than one single large commit? For me it's much easier to review step by step by means of small, clean and dedicated commits than one commit but I saw in other PRs the advice to squash all commits so I'm curious what approach is better here?

**Pull request merged**
