### PR TITLE
fixup #1428

### LINKED ISSUE #1681: Regression: Range violation
### System information

- Dub version: 1.15.0-beta.1+2-g3936dbf
- Platform: macOS
- DMD version: 2.085.1

### Bug Description

When executing Dub in a certain way using `spawnProcess` I get a Range violation error.

### How to reproduce?

1. Create a Dub project with the following content:

dub.json:

```json
{
    "name": "foo",
    "targetType": "executable",

    "configurations": [
        {
            "name": "unittest",
            "mainSourceFile": "test.d"
        },
    ],
}
```

test.d:

```d
void main()
{
    import std.process : spawnProcess, wait;
    spawnProcess(["/full/path/to/dub", "build", "--vverbose", ""]).wait();
}
```

2. Execute `dub test`

Replace `/full/path/to/dub` with the full path to the Dub executable. The issue here is the third empty argument. This is what's causing the range violation. I assume when Dub is normally executed from the shell no trailing empty argument will be passed through, even if trailing whitespace is added when executing the Dub command.

### Logs

Verbose output of Dub executed through `spawnProcess`:

```
Range violation
Full exception: core.exception.RangeError@source/dub/commandline.d(2225): Range violation
----------------
??:? _d_arrayboundsp [0x533717d]
~/.dvm/compilers/dmd-2.085.1/osx/bin/../../src/druntime/import/object.d:342 pure nothrow @safe dub.commandline.splitPackageName(immutable(char)[]).PackageAndVersion dub.commandline.splitPackageName(immutable(char)[]) [0x512bdf6]
~/.dvm/compilers/dmd-2.085.1/osx/bin/../../src/druntime/import/object.d:342 int dub.commandline.BuildCommand.execute(dub.dub.Dub, immutable(char)[][], immutable(char)[][]) [0x5123e1f]
~/.dvm/compilers/dmd-2.085.1/osx/bin/../../src/druntime/import/object.d:342 int dub.commandline.runDubCommandLine(immutable(char)[][]) [0x511fba2]
source/app.d:14 _Dmain [0x5113b6f]
```

### PR DESCRIPTION
**Pull request by MartinNowak**
- fix #1681 - range violation with empty arg
- add output if package wasn't found online
- add non-interactive mode that doesn't search for online packages

### CODE REVIEW

**Comment by MartinNowak** [comment]
Sorry for craming multiple things into this PR.

**Comment by jacob-carlborg** [comment]
The fix for #1681 looks good to me.

**Comment by MartinNowak** [comment]
Let me merge the non-controversial stuff before the last commit so I can build a release candidate.

**Comment by wilzbach** [comment]
I don't think it's super controversial. Thanks a lot for this!

**Pull request merged**
