### PR TITLE
Enforce that recipe comments are the first thing in the source file.

### PR DESCRIPTION
**Pull request by s-ludwig**
Apart from the optional shebang line...

This is a temporary replacement for #872.

### CODE REVIEW

**Comment by s-ludwig** [comment]
@rjmcguire: I've made this alternative to keep the changes minimal for now and so that we can work on #872 without having to fit into the 1.0.0 release schedule (which is already overdue).

**Comment by rjmcguire** [comment]
Thanks, I had sorted out the problems with both my implementations but I can't figure out how to update my pull-requests, think I may have messed up my local repo by not branching before doing my changes.

**Comment by s-ludwig** [comment]
While working on it, you can just add additional commits to the branch that is used for the PR and those will appear automatically. Once everything is finished, you can use rebase/squash to merge the commits together. Alternatively, if the PR is supposed to be a single commit anyway, `git commit --amend` will overwrite the latest commit instead of adding a new one, so that no rebase is necessary at the end. In both cases, you'll have to push the changes with `--force`, to force overwriting the commit history of the branch on github.

**Comment by s-ludwig** [comment]
Merging for rc.1.

**Pull request merged**
