### PR TITLE
Temporarily disable ldc-master as the dustmite test is broken

### PR DESCRIPTION
**Pull request by Geod24**

### CODE REVIEW

**Comment by WebFreak001** [comment]
yes

**Comment by Geod24** [comment]
We can reproduce with:
```shell
~/dlang/install.sh install ldc-latest-ci
source ~/dlang/ldc-b0eab59b/activate
cd $DUB_REPO
cd test/
DUB=dub CURR_DIR=$(pwd) ./dustmite-no-redirect.sh
```

**Comment by Geod24** [comment]
Well let's disable it for the time being.

**Comment by Geod24** [comment]
More stuff broke overnight, AWESOME!

**Comment by CyberShadow** [comment]
Is this Dustmite's fault?

**Comment by Geod24** [comment]
I had a quick look but I don't see what's changed between yesterday and today. LDC is using dustmite from dlang/tools and hasn't updated the version they are using AFAICS.

**Pull request merged**
