### PR TITLE
Manpages

### PR DESCRIPTION
**Pull request by mpevnev**
I've adapted --help messages and recipe file specifications into manpages. Please check them for correctness, especially the *-override, dub.json and dub.sdl pages. With *-overrides it's mostly a guesswork, since --help message is empty apart of options, and dub.json and dub.sdl pages are huge, something might have slipped under the radar. If anything needs to be added/reworded, please inform me.

### CODE REVIEW

**Comment by wilzbach** [comment]
Hmm while this is pretty cool work, I worry quite a bit that this will be outdated soon.
Would it be possible to automatically generate the Manpages, maybe analogous to how the DUB registry displays the docs? 

https://github.com/dlang/dub-registry/blob/master/source/dubregistry/web.d#L591
https://github.com/dlang/dub-registry/blob/master/views/docs.commandline.dt

You might also want to have a look at `showHelp` directly at DUB:

https://github.com/dlang/dub/blob/master/source/dub/commandline.d#L1881

**Comment by mpevnev** [comment]
I've tried help2man, but results were not pretty. However, the structure of help messages is quite regular, so it should be possible to write a parser with some regexes. Any such program would require a bit of manual work to make its output look nicer, but it should help with keeping manpages up-to-date. Give me a few days, this sounds fun.

**Comment by MartinNowak** [comment]
Thanks, nice initiative.

Well the commands and help are already available programmatically, so no parser is needed. Just a tool (in `genmanpages/`) that links against dub (`dependency "dub" path="../"`), calls [`getCommands()`](https://github.com/dlang/dub/blob/b7e48d3f8bb7d0d3d912682f8cff95afc866fd96/source/dub/commandline.d#L43), and produces the man pages from those.
The result in the dub-registry isn't far off from a man page http://code.dlang.org/docs/commandline.

**Comment by mpevnev** [comment]
@MartinNowak Well, by the time you've written this I've nearly finished a parser-based generator. It does most of the work well, but some things would have to be done manually: short descriptions in NAME section are left blank because I have no idea how to extract them from long descriptions and lists in option descriptions are clumped together rather unelegantly. The tool repo is located [here](https://github.com/mpevnev/dub-genmanpage). I'll see what I can do about lists, though.

**Comment by wilzbach** [comment]
> I've nearly finished a parser-based generator. It does most of the work wel

If you are searching for an application of your parser, generating the Manpages and/or the resulting web documentation for DMD frontend, would be awesome.
It's currently entirely maintained by hand and a huge pain as it gets outdated easily...
A couple of pointers:

- https://github.com/dlang/dmd/blob/master/src/ddmd/mars.d#L98
- https://github.com/dlang/dmd/tree/master/docs/man
- https://github.com/dlang/dlang.org/blob/master/dcompiler.dd
- http://dlang.org/dmd.html (redirects based on your OS)

**Comment by BBasile** [comment]
You Must start your commit message with fix `#855 - ...` so that this get closed: https://github.com/dlang/dub/issues/855

**Comment by s-ludwig** [comment]
@mpevnev: If you use the [`getCommands`](https://github.com/dlang/dub/blob/3ecb1e3150806bf01bcb0c2fc7c9be4dd92e8f44/source/dub/commandline.d#L43) function, you can get the short descriptions isolated from the rest. 

The actual options need to be extracted by instantiating the `CommandArgs` struct:
```
// options common to all commands
CommonOptions options;
auto common_args = new CommandArgs(null);
options.prepare(common_args);
foreach (arg; common_args.recognizedArgs) { ... }

// options for each specific command
foreach (grp; getCommands()) {
	foreach (cmd; grp.commands) {
		auto args = new CommandArgs(null);
		cmd.prepare(args);
		foreach (arg; args.recognizedArgs) { ... }
	}
}
```

Command groups also group the individual commands into semantic groups (they have a `.caption` property).

Going this route instead of parsing the output would also simplify the generation process somewhat, as it would work independently of the dub binary.

An possible step would then be to add an additional field with more in-depth documentation to each command, which is only shown in the high-level documentation (man pages, but also on the website). Then only the package recipe format documentation would be left as redundant (of course it is already redundant now, because SDL and JSON are in different files). But I wanted to so something about that at some point anyway.

**Comment by wilzbach** [comment]
FYI: We now generate the DMD MAN page automatically - https://github.com/dlang/dmd/pull/7507. 

The man generation script is pretty simple actually - https://github.com/dlang/dmd/blob/master/docs/gen_man.d

**Comment by wilzbach** [comment]
> Going this route instead of parsing the output would also simplify the generation process somewhat, as it would work independently of the dub binary.

A first step: https://github.com/dlang/dub/pull/1342

**Comment by wilzbach** [comment]
Opened this as an issue for the release archives, https://issues.dlang.org/show_bug.cgi?id=18424

Not so sure how to ping the package maintainers.

**Comment by Geod24** [comment]
Superseded by #1342. Thanks for your work!

**Pull request closed without merging**
